#!/usr/bin/env python

import sys
import numpy as np

COUNT=1000
LATENCY=12.345       # millisec
CONCURRENCY=32
EPOCH=1234567890.0   # Fri Feb 13 15:31:30 PST 2009

def log(msg):
    sys.stderr.write(msg)

if len(sys.argv) > 1:
    count=int(sys.argv[1])
else:
    count=COUNT

if len(sys.argv) > 2:
    latency=float(sys.argv[2])
else:
    latency=LATENCY

if len(sys.argv) > 3:
    concurrency=float(sys.argv[3])
else:
    concurrency=CONCURRENCY

tps = concurrency*1000/latency
interval = 1.0/tps

log("TPS={:.2f}\n".format(tps))


starttime = EPOCH + np.random.exponential(1.0/tps, count).cumsum()
latencies = np.random.exponential(latency, count)
endtime   = starttime + latency/1000

t = np.array([starttime,endtime,latencies]).T
sorted_transactions = t
natural_transactions = t[np.argsort(t[:,1])] # sorted by endtime

np.savetxt('test.out',sorted_transactions, fmt="%.6f", delimiter=',')

